language: node_js
node_js: stable

addons: # Travis CI建议加的，自动更新api
  apt:
    update: true

cache:
  directories: 
  - node_modules # 缓存 node_modules
  
before_install:
  - export TZ='Asia/Shanghai' # 更改时区

# 依赖安装
install:
- npm install # 初次安装，在CI环境中，执行安装npm依赖

# before_script: 

# 构建脚本
script:
  #- hexo d # hexo配置文件中配置git部署到gh-pages分支
  - hexo g # 执行 hexo generate，把文章编译到public中

# GitHub Pages 部署
deploy:
  provider: pages
  skip_cleanup: true
  # 在项目仪表盘的 Settings -> Environment Variables 中配置
  github_token: $blog
  # 将 public 目录下的内容推送到 gh-pages 分支上（必须）
  local_dir: public
  target-branch: gh-pages
  #fqdn: https://github.com/feiniaoying/blog.git （非必需）
  # push到github的用户和邮箱
  name: chenwt
  email: feiniaoying@163.com
  #on:
  #  branch: master

# 分支白名单
branches:
  only:
  - master # CI 只针对分支 master